"""Review artifact storage for dpa_mnt server.

Stores source files, comments, and review logs organised by intervention ID.
Each intervention gets a folder; event-level files are prefixed with evt-{event_id}.
"""

import os
from pathlib import Path
from datetime import datetime, UTC
from typing import Optional

from .constants import REVIEW_STORAGE_PATH


class ReviewStorage:
    """Manages persistent storage of review artifacts.

    Organised by intervention: bc-reviews/{intervention_id}/
    Each event's files are prefixed: evt-{event_id}-{artifact}.
    """

    def __init__(self, base_path: str = REVIEW_STORAGE_PATH):
        self.base_path = Path(base_path)

    def get_review_path(self, intervention_id: int) -> Path:
        review_path = self.base_path / str(intervention_id)
        review_path.mkdir(parents=True, exist_ok=True)
        return review_path

    def _evt_prefix(self, event_id: int) -> str:
        return f"evt-{event_id}"

    def save_source(
        self,
        intervention_id: int,
        event_id: int,
        content: bytes,
        content_type: str,
        source_url: str
    ) -> Path:
        review_path = self.get_review_path(intervention_id)
        prefix = self._evt_prefix(event_id)

        ext_map = {"pdf": "pdf", "html": "html", "text": "txt"}
        ext = ext_map.get(content_type, "txt")
        file_path = review_path / f"{prefix}-source.{ext}"
        file_path.write_bytes(content)

        meta_path = review_path / f"{prefix}-source-url.txt"
        meta_path.write_text(source_url)

        return file_path

    def save_comment(
        self,
        intervention_id: int,
        event_id: int,
        comment_text: str,
        comment_id: Optional[int] = None
    ) -> Path:
        review_path = self.get_review_path(intervention_id)
        prefix = self._evt_prefix(event_id)
        comments_path = review_path / f"{prefix}-comments.md"

        timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")
        separator = "\n" + "=" * 80 + "\n"

        header = f"## Comment"
        if comment_id:
            header += f" #{comment_id}"
        header += f" - {timestamp}\n\n"

        comment_block = header + comment_text + separator

        with comments_path.open('a') as f:
            if comments_path.stat().st_size == 0:
                f.write(f"# Review Comments - Event {event_id}\n\n")
                f.write(f"*Generated by Buzessa Claudini automated review system*\n")
                f.write(separator)
            f.write(comment_block)

        return comments_path

    def save_log(
        self,
        intervention_id: int,
        event_id: int,
        source_url: str,
        fields_validated: list[str],
        issues_found: list[str],
        decision: str,
        actions_taken: list[str]
    ) -> Path:
        review_path = self.get_review_path(intervention_id)
        prefix = self._evt_prefix(event_id)
        log_path = review_path / f"{prefix}-review-log.md"

        timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")

        content = f"""# Review Log - Event {event_id}

**Review Date:** {timestamp}
**Decision:** {decision}
**Source:** {source_url}

---

## Fields Validated

"""
        if fields_validated:
            for field in fields_validated:
                content += f"- {field}\n"
        else:
            content += "*No specific fields validated*\n"

        content += "\n---\n\n## Issues Found\n\n"
        if issues_found:
            for issue in issues_found:
                content += f"- {issue}\n"
        else:
            content += "*No issues found - entry validated successfully*\n"

        content += "\n---\n\n## Actions Taken\n\n"
        if actions_taken:
            for action in actions_taken:
                content += f"- {action}\n"
        else:
            content += "*No actions required*\n"

        content += f"\n---\n\n*Review conducted by Buzessa Claudini automated system*\n"

        log_path.write_text(content)
        return log_path

    def get_source_path(self, intervention_id: int, event_id: int) -> Optional[Path]:
        review_path = self.get_review_path(intervention_id)
        prefix = self._evt_prefix(event_id)
        for ext in ["pdf", "html", "txt"]:
            source_path = review_path / f"{prefix}-source.{ext}"
            if source_path.exists():
                return source_path
        return None

    def review_exists(self, intervention_id: int, event_id: int) -> bool:
        review_path = self.base_path / str(intervention_id)
        log_path = review_path / f"evt-{event_id}-review-log.md"
        return log_path.exists()
