"""Review artifact storage for gta_mnt server.

Stores source files, comments, and review logs for each reviewed StateAct.
"""

import os
from pathlib import Path
from datetime import datetime, UTC
from typing import Optional

from .constants import REVIEW_STORAGE_PATH


class ReviewStorage:
    """Manages persistent storage of review artifacts.

    Each StateAct gets a dedicated folder containing:
    - source.{pdf|html|txt} - Downloaded source file
    - comments.md - All review comments
    - review-log.md - Review activity log
    """

    def __init__(self, base_path: str = REVIEW_STORAGE_PATH):
        """Initialize storage with base path.

        Args:
            base_path: Root directory for review artifacts
        """
        self.base_path = Path(base_path)

    def get_review_path(self, state_act_id: int) -> Path:
        """Get path to review folder for a StateAct.

        Args:
            state_act_id: StateAct ID

        Returns:
            Path to review folder (created if doesn't exist)
        """
        review_path = self.base_path / str(state_act_id)
        review_path.mkdir(parents=True, exist_ok=True)
        return review_path

    def save_source(
        self,
        state_act_id: int,
        content: bytes,
        content_type: str,
        source_url: str
    ) -> Path:
        """Save source file to review folder.

        Args:
            state_act_id: StateAct ID
            content: File content as bytes
            content_type: File type (pdf, html, txt)
            source_url: Original source URL

        Returns:
            Path to saved file
        """
        review_path = self.get_review_path(state_act_id)

        # Determine file extension
        ext_map = {
            "pdf": "pdf",
            "html": "html",
            "text": "txt"
        }
        ext = ext_map.get(content_type, "txt")

        file_path = review_path / f"source.{ext}"

        # Write binary content
        file_path.write_bytes(content)

        # Also save source URL for reference
        meta_path = review_path / "source-url.txt"
        meta_path.write_text(source_url)

        return file_path

    def save_comment(
        self,
        state_act_id: int,
        comment_text: str,
        comment_id: Optional[int] = None
    ) -> Path:
        """Append comment to comments.md file.

        Args:
            state_act_id: StateAct ID
            comment_text: Comment text (markdown formatted)
            comment_id: Optional comment ID from API

        Returns:
            Path to comments.md file
        """
        review_path = self.get_review_path(state_act_id)
        comments_path = review_path / "comments.md"

        # Format comment with timestamp and ID
        timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")
        separator = "\n" + "="*80 + "\n"

        header = f"## Comment"
        if comment_id:
            header += f" #{comment_id}"
        header += f" - {timestamp}\n\n"

        comment_block = header + comment_text + separator

        # Append to file (create if doesn't exist)
        with comments_path.open('a') as f:
            # Add file header if new file
            if comments_path.stat().st_size == 0:
                f.write(f"# Review Comments - StateAct {state_act_id}\n\n")
                f.write(f"*Generated by Sancho Claudino automated review system*\n")
                f.write(separator)

            f.write(comment_block)

        return comments_path

    def save_log(
        self,
        state_act_id: int,
        source_url: str,
        fields_validated: list[str],
        issues_found: list[str],
        decision: str,
        actions_taken: list[str]
    ) -> Path:
        """Save or update review log.

        Args:
            state_act_id: StateAct ID
            source_url: Source URL used for validation
            fields_validated: List of fields checked
            issues_found: List of issues discovered (empty if none)
            decision: "APPROVE" or "DISAPPROVE"
            actions_taken: List of actions (comments posted, status changed, etc.)

        Returns:
            Path to review-log.md file
        """
        review_path = self.get_review_path(state_act_id)
        log_path = review_path / "review-log.md"

        timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")

        # Build log content
        content = f"""# Review Log - StateAct {state_act_id}

**Review Date:** {timestamp}
**Decision:** {decision}
**Source:** {source_url}

---

## Fields Validated

"""

        if fields_validated:
            for field in fields_validated:
                content += f"- {field}\n"
        else:
            content += "*No specific fields validated*\n"

        content += "\n---\n\n## Issues Found\n\n"

        if issues_found:
            for issue in issues_found:
                content += f"- {issue}\n"
        else:
            content += "*No issues found - entry validated successfully*\n"

        content += "\n---\n\n## Actions Taken\n\n"

        if actions_taken:
            for action in actions_taken:
                content += f"- {action}\n"
        else:
            content += "*No actions required*\n"

        content += f"\n---\n\n*Review conducted by Sancho Claudino automated system*\n"

        # Write log file (overwrite if exists for latest state)
        log_path.write_text(content)

        return log_path

    def get_source_path(self, state_act_id: int) -> Optional[Path]:
        """Get path to source file if it exists.

        Args:
            state_act_id: StateAct ID

        Returns:
            Path to source file or None if not found
        """
        review_path = self.get_review_path(state_act_id)

        # Check for any source file
        for ext in ["pdf", "html", "txt"]:
            source_path = review_path / f"source.{ext}"
            if source_path.exists():
                return source_path

        return None

    def get_comments_path(self, state_act_id: int) -> Path:
        """Get path to comments file.

        Args:
            state_act_id: StateAct ID

        Returns:
            Path to comments.md (may not exist yet)
        """
        review_path = self.get_review_path(state_act_id)
        return review_path / "comments.md"

    def get_log_path(self, state_act_id: int) -> Path:
        """Get path to review log file.

        Args:
            state_act_id: StateAct ID

        Returns:
            Path to review-log.md (may not exist yet)
        """
        review_path = self.get_review_path(state_act_id)
        return review_path / "review-log.md"

    def review_exists(self, state_act_id: int) -> bool:
        """Check if a review has been conducted for this StateAct.

        Args:
            state_act_id: StateAct ID

        Returns:
            True if review log exists
        """
        log_path = self.get_log_path(state_act_id)
        return log_path.exists()
