"""Unit tests for ReviewStorage artifact persistence."""

import pytest
from pathlib import Path
from datetime import datetime, UTC
from gta_mnt.storage import ReviewStorage


@pytest.fixture
def temp_storage(tmp_path):
    """Create ReviewStorage with temporary base path."""
    return ReviewStorage(base_path=str(tmp_path))


@pytest.fixture
def sample_pdf_bytes():
    """Sample PDF content as bytes."""
    return b"%PDF-1.4\nSample PDF content"


@pytest.fixture
def sample_html_bytes():
    """Sample HTML content as bytes."""
    return b"<html><body><h1>Test</h1></body></html>"


# ============================================================================
# Path Management Tests
# ============================================================================


def test_get_review_path_creates_directory(temp_storage):
    """Test that get_review_path creates directory if it doesn't exist."""
    state_act_id = 12345
    review_path = temp_storage.get_review_path(state_act_id)

    assert review_path.exists()
    assert review_path.is_dir()
    assert review_path.name == str(state_act_id)


def test_get_review_path_idempotent(temp_storage):
    """Test that get_review_path is idempotent."""
    state_act_id = 12345
    path1 = temp_storage.get_review_path(state_act_id)
    path2 = temp_storage.get_review_path(state_act_id)

    assert path1 == path2
    assert path1.exists()


# ============================================================================
# Source Saving Tests
# ============================================================================


def test_save_pdf_source(temp_storage, sample_pdf_bytes):
    """Test saving PDF source file."""
    state_act_id = 12345
    source_url = "s3://bucket/file.pdf"

    file_path = temp_storage.save_source(
        state_act_id=state_act_id,
        content=sample_pdf_bytes,
        content_type="pdf",
        source_url=source_url
    )

    assert file_path.exists()
    assert file_path.name == "source.pdf"
    assert file_path.read_bytes() == sample_pdf_bytes

    # Check source URL metadata
    url_file = file_path.parent / "source-url.txt"
    assert url_file.exists()
    assert url_file.read_text() == source_url


def test_save_html_source(temp_storage, sample_html_bytes):
    """Test saving HTML source file."""
    state_act_id = 12345
    source_url = "https://example.com/policy.html"

    file_path = temp_storage.save_source(
        state_act_id=state_act_id,
        content=sample_html_bytes,
        content_type="html",
        source_url=source_url
    )

    assert file_path.exists()
    assert file_path.name == "source.html"
    assert file_path.read_bytes() == sample_html_bytes


def test_save_text_source(temp_storage):
    """Test saving text source file."""
    state_act_id = 12345
    source_url = "https://example.com/policy.txt"
    text_content = b"Plain text policy document"

    file_path = temp_storage.save_source(
        state_act_id=state_act_id,
        content=text_content,
        content_type="text",
        source_url=source_url
    )

    assert file_path.exists()
    assert file_path.name == "source.txt"
    assert file_path.read_bytes() == text_content


def test_save_source_overwrites_existing(temp_storage, sample_pdf_bytes):
    """Test that saving source overwrites existing file."""
    state_act_id = 12345
    source_url = "s3://bucket/file.pdf"

    # Save first time
    temp_storage.save_source(
        state_act_id=state_act_id,
        content=sample_pdf_bytes,
        content_type="pdf",
        source_url=source_url
    )

    # Save again with different content
    new_content = b"%PDF-1.4\nUpdated content"
    file_path = temp_storage.save_source(
        state_act_id=state_act_id,
        content=new_content,
        content_type="pdf",
        source_url=source_url
    )

    assert file_path.read_bytes() == new_content


# ============================================================================
# Comment Saving Tests
# ============================================================================


def test_save_first_comment_creates_file(temp_storage):
    """Test that saving first comment creates comments.md with header."""
    state_act_id = 12345
    comment_text = "This is a test comment."

    comments_path = temp_storage.save_comment(
        state_act_id=state_act_id,
        comment_text=comment_text,
        comment_id=100
    )

    assert comments_path.exists()
    content = comments_path.read_text()

    # Check header
    assert f"# Review Comments - StateAct {state_act_id}" in content
    assert "*Generated by Sancho Claudino automated review system*" in content

    # Check comment
    assert "## Comment #100" in content
    assert comment_text in content


def test_save_multiple_comments_appends(temp_storage):
    """Test that multiple comments append to file."""
    state_act_id = 12345

    # Save first comment
    temp_storage.save_comment(
        state_act_id=state_act_id,
        comment_text="First comment",
        comment_id=100
    )

    # Save second comment
    comments_path = temp_storage.save_comment(
        state_act_id=state_act_id,
        comment_text="Second comment",
        comment_id=101
    )

    content = comments_path.read_text()

    # Both comments should be present
    assert "## Comment #100" in content
    assert "First comment" in content
    assert "## Comment #101" in content
    assert "Second comment" in content


def test_save_comment_without_id(temp_storage):
    """Test saving comment without comment_id."""
    state_act_id = 12345
    comment_text = "Comment without ID"

    comments_path = temp_storage.save_comment(
        state_act_id=state_act_id,
        comment_text=comment_text
    )

    content = comments_path.read_text()

    # Should have comment marker but no ID
    assert "## Comment - " in content
    assert comment_text in content


# ============================================================================
# Review Log Tests
# ============================================================================


def test_save_review_log_approve(temp_storage):
    """Test saving review log with APPROVE decision."""
    state_act_id = 12345
    source_url = "https://example.com/policy.pdf"
    fields_validated = ["Title", "Implementation date", "Source URL"]
    issues_found = []
    decision = "APPROVE"
    actions_taken = ["Framework tag added (id=495)"]

    log_path = temp_storage.save_log(
        state_act_id=state_act_id,
        source_url=source_url,
        fields_validated=fields_validated,
        issues_found=issues_found,
        decision=decision,
        actions_taken=actions_taken
    )

    assert log_path.exists()
    content = log_path.read_text()

    # Check structure
    assert f"# Review Log - StateAct {state_act_id}" in content
    assert f"**Decision:** {decision}" in content
    assert f"**Source:** {source_url}" in content

    # Check fields
    for field in fields_validated:
        assert f"- {field}" in content

    # Check no issues
    assert "*No issues found - entry validated successfully*" in content

    # Check actions
    for action in actions_taken:
        assert f"- {action}" in content


def test_save_review_log_disapprove(temp_storage):
    """Test saving review log with DISAPPROVE decision."""
    state_act_id = 12345
    source_url = "https://example.com/policy.pdf"
    fields_validated = ["Title", "Implementation date"]
    issues_found = [
        "Title mismatch: Expected 'Policy X', found 'Policy Y'",
        "Implementation date incorrect: Should be 2025-01-15"
    ]
    decision = "DISAPPROVE"
    actions_taken = [
        "Comment posted (id=123)",
        "Status changed to 'Under revision' (status_id=6)"
    ]

    log_path = temp_storage.save_log(
        state_act_id=state_act_id,
        source_url=source_url,
        fields_validated=fields_validated,
        issues_found=issues_found,
        decision=decision,
        actions_taken=actions_taken
    )

    content = log_path.read_text()

    # Check decision
    assert f"**Decision:** {decision}" in content

    # Check issues
    for issue in issues_found:
        assert f"- {issue}" in content

    # Check actions
    for action in actions_taken:
        assert f"- {action}" in content


def test_save_review_log_overwrites(temp_storage):
    """Test that saving review log overwrites existing file."""
    state_act_id = 12345

    # Save first log
    temp_storage.save_log(
        state_act_id=state_act_id,
        source_url="https://example.com/v1.pdf",
        fields_validated=["Title"],
        issues_found=[],
        decision="APPROVE",
        actions_taken=[]
    )

    # Save second log
    log_path = temp_storage.save_log(
        state_act_id=state_act_id,
        source_url="https://example.com/v2.pdf",
        fields_validated=["Title", "Date"],
        issues_found=["Title mismatch"],
        decision="DISAPPROVE",
        actions_taken=["Comment posted"]
    )

    content = log_path.read_text()

    # Should only have second log
    assert "v2.pdf" in content
    assert "**Decision:** DISAPPROVE" in content
    assert "v1.pdf" not in content
    assert "**Decision:** APPROVE" not in content


# ============================================================================
# Helper Method Tests
# ============================================================================


def test_get_source_path_pdf(temp_storage, sample_pdf_bytes):
    """Test get_source_path returns PDF file."""
    state_act_id = 12345

    temp_storage.save_source(
        state_act_id=state_act_id,
        content=sample_pdf_bytes,
        content_type="pdf",
        source_url="s3://bucket/file.pdf"
    )

    source_path = temp_storage.get_source_path(state_act_id)
    assert source_path is not None
    assert source_path.name == "source.pdf"


def test_get_source_path_none_when_no_file(temp_storage):
    """Test get_source_path returns None when no source file exists."""
    state_act_id = 12345

    # Create review folder but no source file
    temp_storage.get_review_path(state_act_id)

    source_path = temp_storage.get_source_path(state_act_id)
    assert source_path is None


def test_review_exists_true(temp_storage):
    """Test review_exists returns True when review log exists."""
    state_act_id = 12345

    temp_storage.save_log(
        state_act_id=state_act_id,
        source_url="https://example.com",
        fields_validated=[],
        issues_found=[],
        decision="APPROVE",
        actions_taken=[]
    )

    assert temp_storage.review_exists(state_act_id) is True


def test_review_exists_false(temp_storage):
    """Test review_exists returns False when no review log."""
    state_act_id = 12345

    # Create folder but no log
    temp_storage.get_review_path(state_act_id)

    assert temp_storage.review_exists(state_act_id) is False


def test_get_comments_path(temp_storage):
    """Test get_comments_path returns correct path."""
    state_act_id = 12345
    comments_path = temp_storage.get_comments_path(state_act_id)

    assert comments_path.name == "comments.md"
    assert str(state_act_id) in str(comments_path)


def test_get_log_path(temp_storage):
    """Test get_log_path returns correct path."""
    state_act_id = 12345
    log_path = temp_storage.get_log_path(state_act_id)

    assert log_path.name == "review-log.md"
    assert str(state_act_id) in str(log_path)
